services:
  web:
    build: .
    container_name: vote-app
    ports:
      - "6243:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=voteproject.settings
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
